name: "L. Gabriel Miller"
description: "Computer nerd renaissance man"
encoding: UTF-8

url: "http://www.gabrielmiller.org/"

permalink: pretty #"/:year/:title"

highlighter: rouge

sass:
  style: compressed
  sass_dir: css